// Bundles the Super Mario Bros level texts of the VGLC into src/smbdata.js.
//
//   node web/tools/smb-import.mjs
//
// Source: The Video Game Level Corpus (MIT License),
// https://github.com/TheVGLC/TheVGLC/tree/master/Super%20Mario%20Bros/Processed
// The text files are kept in web/levels/smb/. The conversion to the map
// format of the game happens at run time in src/smb.js.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.resolve(here, '..', 'levels', 'smb');
const OUT = path.resolve(here, '..', 'src', 'smbdata.js');

const files = fs.readdirSync(DIR).filter((f) => /^mario-\d-\d\.txt$/.test(f)).sort();
let out = '// Generated by web/tools/smb-import.mjs from the Video Game Level Corpus\n';
out += '// (TheVGLC, MIT License: web/levels/smb/LICENSE-VGLC.md). Do not edit.\n\n';
out += 'export const SMB_TEXT = {\n';
for (const f of files) {
  const id = f.match(/mario-(\d-\d)/)[1];
  const lines = fs.readFileSync(path.join(DIR, f), 'utf8').replace(/\r/g, '').split('\n').filter(Boolean);
  out += `  '${id}': [\n${lines.map((l) => `    '${l}',`).join('\n')}\n  ],\n`;
}
out += '};\n';
fs.writeFileSync(OUT, out);
console.log(`Wrote ${OUT}: ${files.length} levels`);
